title = "Haibin Ren - Personal Website"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true


# [languages]
# [languages.en]
# title = "Haibin Ren"
# contentDir = "content"
# languageDirection = 'rtl' for Right-To-Left languages


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
math = true
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-gray"
recent_posts_number = 1

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"